### ISSUE TITLE
语文学习计划 | Schtonn's Blog

### ISSUE THREAD

**Issue by schtonn** [schtonn/schtonn.github.io#1]
https://schtonn.github.io/post/cn-plan/ 

 薄弱项

作文

写日记

每天固定9:00-9:30
内容不必精美
一周写五天，两天机动
字数逐步增加，100字起步

读书

作文辅导书为主 作文大全等
其他书籍为辅

阅读题

读书

文学性书籍
名著阅读 课程化丛书

做...

**Comment by schtonn** [comment]
好

**Comment by schtonn** [comment]
评论可以用了？？！

**Comment by schtonn** [comment]
蛤蟆
### 蛤蟆

**Comment by Yonghong** [comment]
1. 每天写日记大概花费30分钟
2. 读作文相关的书（同时做题），估计30分钟
3. 阅读每天至少保证30分钟，加上录音（大概15分钟），每天估计需要45分钟
4. 文常和文言文交替进行学习，周一、三、五学习文常，周二、四、六学习文言文，每次不少于30分钟
由此，每天预计花135分钟在语文学习上。
**成功贵在坚持**

**Comment by schtonn** [comment]
> @Yonghong
> 1. 每天写日记大概花费30分钟
> 2. 读作文相关的书（同时做题），估计30分钟
> 3. 阅读每天至少保证30分钟，加上录音（大概15分钟），每天估计需要45分钟
> 4. 文常和文言文交替进行学习，周一、三、五学习文常，周二、四、六学习文言文，每次不少于30分钟
> 由此，每天预计花135分钟在语文学习上。
> **成功贵在坚持**

ok
